### ISSUE TITLE
Updated FitSeq2 Script Is Not Running

### ISSUE THREAD

**Issue by igorsdub** [FangfeiLi05/FitSeq2#1]
Hi, @amahadevan99, thanks for adding error estimation for fitness value. That is a very useful statistic! However, I found an issue with the current version of the FitSeq2 (commit 8304b126899b23420a5e8412b1668c09cfcc0b49 on Oct 19 2024).

## Expected Behaviour
FitSeq2 estimates error in fitness and error in initial cell number which can be found in `output_filename_FitSeq2_Result.csv` file.

## Current Behaviour
I've run `GoThrough.ipynb`, and GrowthSimulation and FitSeq section works as expected. However, FitSeq2 gives an error during optimisation process. Also, I've noticed that the committed FitSeq2 output files are still from the previous version of FitSeq2 before error estimation introduction. The format is the old one with no column that contains errors.

## Possible Solution
Re-run the code with the test data (which is not available in repo) and commit corrected FitSeq2 version that is compatible with GrowthSimulation output data.

## Steps to Reproduce
Run `Gothrough.ipynb`.

### GrowthSimulation ✅
```python
dir_input = './example/'
dir_output = './example/'
command = './src/GrowthSimulation.py -t {0}simu_input_time_points.csv -s {0}simu_input_fitness.csv -o {1}simu_output'.format(
    dir_input, 
    dir_output
    )
os.system(command)
```
```
100%|██████████████████████████████████████████| 21/21 [00:03<00:00,  6.16it/s]
```
### FitSeq ✅
```python
import os

dir_input = './example/'
dir_output = './example/'

command = './src/FitSeq.py -i {0}simu_output_0_EvoSimulation_Read_Number.csv -t {0}fitseq2_input_time_points.csv -n 3 -o {1}output'.format(
    dir_input, 
    dir_output
    )

os.system(command)
```
```
--- iteration 1 ...
100%|█████████████████████████████████| 10000/10000 [00:00<00:00, 11315.90it/s]
    computing time: 1.36529 seconds
--- iteration 2 ...
100%|█████████████████████████████████| 10000/10000 [00:00<00:00, 10884.68it/s]
10080.307575790735
    computing time: 1.37293 seconds
--- iteration 3 ...
100%|█████████████████████████████████| 10000/10000 [00:00<00:00, 11012.38it/s]
1299.6235904944479
    computing time: 1.38719 seconds
Total computing time: 4.12576 seconds
```

### FitSeq2 ❌

```python
import os

dir_input = './example/'
dir_output = './example/'

command = './src/FitSeq2.py -i {0}simu_output_0_EvoSimulation_Read_Number.csv -t {0}fitseq2_input_time_points.csv -dt 4 -n 2 -o {1}output'.format(
    dir_input, 
    dir_output
    )

os.system(command)
```
```
--- iteration 1 ...
Traceback (most recent call last):
  File "/home/FitSeq2/./src/FitSeq2.py", line 451, in <module>
    main()
    ~~~~^^
  File "/home/FitSeq2/./src/FitSeq2.py", line 448, in main
    process(r,t,cell_depth,delta_t,c,opt_algorithm,max_iter_num,parallelize,output_prefix)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/FitSeq2/./src/FitSeq2.py", line 363, in process
    my_obj.infer_fitnesses()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/FitSeq2/./src/FitSeq2.py", line 335, in infer_fitnesses
    self.run_iteration()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/FitSeq2/./src/FitSeq2.py", line 241, in run_iteration
    self.result_n0[i],self.result_s[i] = self.optimize_n0_s(i)
                                         ~~~~~~~~~~~~~~~~~~^^^
  File "/home/FitSeq2/./src/FitSeq2.py", line 140, in optimize_n0_s
    opt_output = differential_evolution(
        func = self.objective_func,
        seed = 1,
        bounds = self.bounds
        )
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/scipy/optimize/_differentialevolution.py", line 503, in differential_evolution
    ret = solver.solve()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/scipy/optimize/_differentialevolution.py", line 1230, in solve
    result = minimize(self.func,
                      np.copy(DE_result.x),
                      method=polish_method,
                      bounds=self.limits.T,
                      constraints=self.constraints)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/scipy/optimize/_minimize.py", line 731, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
                           callback=callback, **options)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/scipy/optimize/_lbfgsb_py.py", line 407, in _minimize_lbfgsb
    f, g = func_and_grad(x)
           ~~~~~~~~~~~~~^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/scipy/optimize/_differentiable_functions.py", line 343, in fun_and_grad
    self._update_fun()
    ~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/scipy/optimize/_differentiable_functions.py", line 294, in _update_fun
    fx = self._wrapped_fun(self.x)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/scipy/optimize/_differentiable_functions.py", line 20, in wrapped
    fx = fun(np.copy(x), *args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/scipy/_lib/_util.py", line 441, in __call__
    return self.f(x, *self.args)
           ~~~~~~^^^^^^^^^^^^^^^
  File "/home/FitSeq2/./src/FitSeq2.py", line 129, in objective_func
    output = self.traj_LL(x[0], x[1])
  File "/home/FitSeq2/./src/FitSeq2.py", line 122, in traj_LL
    integrand_log = self.traj_LL_from_n(n0, s)['optimal_value'] + r0_loglikelihood
                    ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/FitSeq2/./src/FitSeq2.py", line 99, in traj_LL_from_n
    nu_vec = np.linalg.solve(M_matrix, b_vec)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/numpy/linalg/_linalg.py", line 410, in solve
    r = gufunc(a, b, signature=signature)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/fitseq2/lib/python3.13/site-packages/numpy/linalg/_linalg.py", line 104, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

## Systems Info
OS: Sonoma 14.7
CPU: Apple M2
RAM: 16 GB

I'm using Conda environment with package versions provided in `requirements.txt` as recommended in the README.
```yml
mamba 1.5.9
conda 24.9.2
python 3.12
notebook 7.1.2
ipykernel 6.29.4
numpy 1.26.4
pandas 2.2.1
tqdm 4.66.2
multiprocess 0.70.16
scipy 1.13.0
```

**Comment by igorsdub** [comment]
Solved in c8afdb155bbf63c6ee8841b44f86328d5e4612ec
